dist: trusty
language: java
sudo: required
jdk:
- oraclejdk8
- openjdk8
before_script:
- wget "https://github.com/nats-io/gnatsd/releases/download/$gnatsd_version/gnatsd-$gnatsd_version-linux-amd64.zip" -O tmp.zip
- unzip tmp.zip
- mv gnatsd-$gnatsd_version-linux-amd64 gnatsd
before_install:
- openssl aes-256-cbc -K $encrypted_f07928735f08_key -iv $encrypted_f07928735f08_iv -in .travis/nats.travis.gpg.enc -out .travis/nats.travis.gpg -d
install:
- "./gradlew -PossrhUsername=${SONATYPE_USERNAME} -PossrhPassword=${SONATYPE_PASSWORD} -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE} -Psigning.secretKeyRingFile=.travis/nats.travis.gpg assemble -x signArchives"
script:
- "./gradlew check"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./gradlew test jacocoTestReport coveralls"
- "./deploy.sh"
env:
  global:
  - gnatsd_version=v1.1.0
  - gnatsd_path=$TRAVIS_BUILD_DIR/gnatsd/gnatsd
  - secure: jDp7fGgZgQb2BCqqy/HNrqJAVgri1DL6zb6KHy1ZSQsPbvN9690V7iVbwdT00UkmuAH7NybEKPA0GsEOWlFADnpM+bN3WPsnZioebWwcqydt8UQKRo+2BWMqNJPQlEhaxSDYMHENoyi2GX3Vh9LYMrKrYgPXTs37/+ipB8Df4sh7F3+T4GZgDPsusiiVpyLqWMDilpK8YQcPCHUa4KI3kyczyZd2ExYnmDu93OXOfAyZcV4JYaRGdYL/MqN2wjjfakvs2CF2YqFVGntVYqb3R/9uXeauqdr58D6DLdYbDyJSSvsEs/BqbR/gQz6xpNOVidxSakWnA13f5ovZ8840BpkFDD6/j1QXi6GYSXcN45z5T9cA/3QjRpCeu2ebDj+FgwAqU2xVLCMlaiz4wz9LYMn+FYQ90mYNdloAoUj8+tbvgfzOkTni2vy3fuReUccuBDKmMudOtIU46cM+yom32+z/tkXp95eG/iEe9olw3h+tGNzC4mZRLn/+P9BXaMT+/TlFmi/JX94cyR2WgwLAVwE7dJyYX/f0exLo96PEA5pH76kVH79IByV8yR3zQdv9EfQGvAiIH0g4pPQjoYnvdmak811YId6Dd0i2bo46N39gagV3KywW3xav8DkaSr0L42breJWn8oAkEEF6aQnXgbCpr0HBs4bxFE60h+/tCLY=
  - secure: BUmXctiFngqD0iYPuEEJ1hWXeF+2eqj5ahEiHRNUSuXNnUKSTxLeLfTbkE+DkDJCiNECsC9/yndihI/RUInoJao/YZoHQ7XcE1e00PcP16ou+1S94uddvlpr5o6WQmx0hpzKsit7SRg5lgyukNRxyTd8bCmSuC7zoecxxcY8rpbl9OEjzkNrUUOmXDNol+y7WCV57HtHhEH66s25ave5Fcw5GZWIhPsl1iWIzPtqjDpiF1Ll205SAYTB9feQqoam13aLhF+k3Y/AQ1sdJ70w9UImldKFyq75QW6UHRQ+NG98FHhlz41MYGmGDtJHHYge5LJK0zgmaAYSuCWbIBP+qqZtLO8SXVPT80Cu0EHWmq8uK5bEOpgMaoz0FeKx737cYrEmrV0isLhj7tV0VhVK7b4wxIfYpA9KuZsjgxSdrPAl1F6Bg2kpzjP9yi+Yv+UIZ/xrC0IwvgTQhbCacNMpLtm+IN5GEAGBrhX3R8+91JRaEIgk5OxLulsHUckAAeV+9ebhX1YvXyqcDqh8lzvfQ9mwlX/QrsMOWt8W5ZC+ddnW1Tctrrq5RgfkBCQ/CNpO4sXPxVNk1q2hWoXEKHoijrcLwkkWS/hT6yV4s9ggLWl2KqTRzrdeDOur76cFIFsld1Vyknqq1pDHtnRMHsSBEgh0mEfZJlv8cp1j1qb+M7g=
  - secure: CNpzsGzdR62dy4CxsMqhSYYa4EkZdg8PrHIDBNA7n+iJp659Acfo0SPhp5igjPGh5CEenKw1GL3GJKiiELGAXre8UaPxM0Hzc64UNkYutk3vYl5hmIUcIsHTTfzYfZIy/LDXaUv3qkiwx9KwETwL6uokqJq0vFNxhjlsqfs43RL+dznsVIluJpzaxpJUoMuOQvOBnMHN5n4yPv6HKN7BFQrj+7ClacMkA7D2OfDbHdXgEPj6wA939n+hwhJbxnRuCOEJYSYOcJuirzD5iYsZjaRptaHMXapc4OLWmkA+eDXW3ZhWGhHshBcaOkHYGBIekdvgDsP3D1wakc/NkgvVyiSo+Brzwazopn85S9YbcygpnQniEz90gPCTmCPbGTevA8ch13nUzV/ehHn/09G5ezrnSA/lGit2BvMi1aLs7tMVJ0X57JGA+PTcQu9PE68TqqrTxIKRsnehyrLjJ0sze29uw5Iz9ujUuCTLAJem+SBi0k+KcqQs7uBzDmaZlZ+ZFInqmJQaRJ8TplmseEdvR+cAFqzf4VHjE4g8cXuVROnqe8firPBd0Zmw5snoJ6v7xXTC/z2pRuaGI5r5qJN+AFZK1FeBq7DEnL4VtwenNzCmz4EPg1WaihqYlQ/WDVdlaQ6utSUu7Jct/LsjRl1C0T+p9wU22KNZLPTPhLQKAXg=
  - secure: rh5ZVjNaklgwnRSizqt2utzkz27FJwny3gWQkx9QlmkRPisrWWAEtkhpc+WUtV5PT3/LPh5GyqFQNmQI6m3vZbf30KS2/vanQagnxs7ZUem7AiVPLVjbhexeFqi28BafhJjI4DNCYKvQb2u1wLwbvHw9hN48WWahJJpuAvnAiren52qmrZITt7HpTU8BTsxtX3pFK6Iqq2EfZQtPwsP7iK5YGC/8N338Kd+0DGkN7hzrMfHc64lyPmeTqFOso1VKPtR4PQIo67etDNBpkMLjP7Xucw0nGYnj7myfbO7q18LD22R+rJ8gAi6bCarFRclUxFtuoiV/br8h5MWdxJmYjQJyivXMLQvLqTh11eXn4pMpiPh6mPPzjH124CU4O7Hqo6KaO4t+stbcrmvGe0SvCl48WZJ++R+ZEpEl8c4y4dpYt/rUi8vobYkzfmAi2UpaKcDTBXQFpAQ+qJwCy4gEyJC0DnquOMYh53RhLpvBH4FFm172oAq9Klti2n4ZGz/MhvJYkF01UFILC0tVRrGX0+y45zx/7PYXuIWLVxPj+3YFowwYdIVi1pK4yiPXqJtR1rrBwvBDu8VI0GOMMkj4nyOGhYjPNvaxSwqkI3Av+RQTBN/pTEpaFZRdxKDWP0d0Bh5p90DXOPG9nmzAnPLArsNNoXnNResXzgN+MEXGs3k=
