dist: trusty
language: java
sudo: required
jdk:
- oraclejdk8
- openjdk8
before_script:
- wget "https://github.com/nats-io/gnatsd/releases/download/$gnatsd_version/gnatsd-$gnatsd_version-linux-amd64.zip"
  -O tmp.zip
- unzip tmp.zip
- mv gnatsd-$gnatsd_version-linux-amd64 gnatsd
before_install:
- openssl aes-256-cbc -K $encrypted_f07928735f08_key -iv $encrypted_f07928735f08_iv
  -in .travis/nats.travis.gpg.enc -out .travis/nats.travis.gpg -d
install:
- "./gradlew assemble -x signArchives"
script:
- "./gradlew check"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./gradlew test jacocoTestReport coveralls"
- "./gradlew uploadArchives"
env:
  global:
  - gnatsd_version=v1.1.0
  - gnatsd_path=$TRAVIS_BUILD_DIR/gnatsd/gnatsd
  - GPG_KEYRING_FILE=.travis/nats.travis.gpg
  - secure: tRQbeTUlgI71KH3JbwL4tTc64BbJWuMlr8fj/SAKTaXWquBMRN6aS2txSrjuJoQjCAWPBsJI+mUdz4iv9cxVWzOM33IqD9x3fmbTksDWoSM9pdq29QRLlapY4aC991qdLGibQ+M+l/ba9Tn31wBO4f7uJeTLJDHHwQF4taJr7PBbVg1nSj0LV2pBJASG9gchPrmPydRF2LZeSxTM3t3LmHZjBYKvdKw20/40q1IupBB5htrxD9rvZQbW0weMlrjzEmipj+TxIhwbtc7bF6Lu7Gbt5AbN6/UzurIdEZS4HmcHPIOlP2L2omZ4epFJ1++xUU4RQtpRBagvZHmqxHNkkeDC2uTeMjOEkMxe5KmJGdr1AcOirfNk9EB4AFKonaPBpVfgvFtNcKKPug9zu43dtwmBxyCPOooPuNciFzeBfU1LAIIpsuOTWh3Pbc2XlMKtftekjgOCR+AD6A9t4h1vpMiqM3BaP91/roMpsdsknc8rXimzroC2pudJog3kvjLuYHLa5Q3XAFFnmOYg+npm+sq+vtP9UygBCPXxbuJJVuAt2YegFR/IHFqh9rSHz1aD3nl5fuFp91bg93pp7GKCcZIUOCW+AVuUldJuQFQ7+p5QRhciIVeiiUETczVGV0fO7+lKfoFFO3uoASSDhr7D/d5Eqa3VKRs+ZT/aVo8e8KI=
  - secure: cg2PaDl9eFLHEzP1C4USjbWys5YcB2sanWJt7BlMi15ygBDrwbCDK54bOEchKWms63dVptOWxGoUzRFc8TtOTjc+27DHhn12NPRDaCq0Axge2Nt//JbjNPEzW1a8wI52q3rfGPKKx8FFPfX1IwVssi/Jn9U6LVQ4RqwSIVXK8I21DwZDoMPc9B9clWYxLgw+zk1Hdoum1UQwmsxqsVutRwaEJ6TgmZX+mjDbm69HDbEApLwg24+hVYq9Aw0OeTo4QkQqhd2oAnVUD6ZVlmJRfXk49hVfCbKGp7pNOn0Ut3qpWaxRZaTLNLXfVLrFTWYAKOqOmsMnb6JoUivFJ2oqpWKj0Ttg+SwGe12WHUoDD5voYQIjSc3OxhXa2IBXUw0jQMKft0+Bcdgkz7j0w0Vh4j9fHOdksGNxhMxbzIUSdTjypTwkgY5iuUSQmdRzt3Aou4SxY2gaThHgEHG20ZIDicbl+cnySOSTM/AYvkYfmifZTC2LrLGnCGI3ECZY589BVmEjvupmVPNoeAojqh760o4Ljpt1x1L5LLpUtixCG30DjmXBK1oBB5soxffVFI4ZPqi/DEdBgPWL1cnbxhR+94qWoGWZOAji481HAfr94a3ipdxBn9IX1uwqH8cY9cc+9NZwbYxXNvtIupqKAVA5k6m+/VcVwT0dzb7ymcTnYWA=
  - secure: HATgocpbebvr6rqRxszkysg2CVALp6cjtTKtsZWC7t3BCXuRIN0a3gaJG0aBuS+i6iVDrWT6rw+yxtQElNZkrMJKGS4Yobtkz2jPgePQrWHVgO4UjeTzcOXjUaVIXcaC/LpqE7DynBeGLs5X6TeBRY0BgRXIsYodSaKWxbFgtNBFZLvTbtLvEbNq6S5EeF31P/xeVWiAlqrXMokGiYYdf+VhnFbQMEYRgBliFjx462J1ERHMBBql5VLuSRVNyUYWaJXLACLfsV/EDBvD2Ty/hUlg8ZAaiKeW/TyKOdXVGWSlFm4F+pLMEC0pOW36vbBoXVwMR28dVpFSuzdOwLvlGQvW48c2oesEvXYUfuQQ+kviJbfVUXVxULUPD6GDIo8EKZjd5UdAGzW07Q2JAEwsBHU+IvkH99ZoZ9sIpUCpDTEGgsSBS4Xu8g3cu+m1AX8wT9BZAWTBhRIroA8tldo8QcZqpO4AfHWictNORFRAfGIUnAkTbSdKkGY8NuWEH/hb8gJntGmSP3mpl8PJwVzYB7c+9sxrkr6l8PybBFiX+ZrCboOX0hfdm/feT09grPZFZrUYNavCZRt0NqNBDSbG9kV4yt1w8+ufZgDwffuzRaRmjm1ZsjqzfziCSl0v1j544ixvV/XkIa6j2u7EQ9WiNTS6/rrIRPKkBCdSIs5+m48=
  - secure: s+9z5afbQJpH9SUBcW5wi4zh0FdjKFdcUxv11nVv/4f3TJ2NtpwJkhWp+xjkP/177MRlIPEI7MnnHV1OIt81vY5/ZtEBi2RVT8ajx+KhH/RM2Vqih1xPtw/eFayUVGiIaLhJAw/RAAVjtUTegbk91Cb7OPv+/dRdYFm/yC65H2HXbp62i6yGS8OYYetuYE1g+aIMi3v7t8jhpqCZ7asVqEWrJnNcb4E/5sHx8zy+hbn5q9HJq2U94RNFQ4AowKCEEXpTcBCIeFrlZrHUumId8qgABEVqIWnyqgmaXVcm8wjO2eQe6acCW9cOtxXOXpjMeTmUdCLuWnK7Ohkt56FKSH66wKlq9wZbtyT8shjeEDIo/nB8d61zxVCEeIHZFLNOmHebf2fLndf+LHzhz9qrESyQuiqX0Wx3OYTqKjgdfV9Nxv34cIW6rb5y74Byyy1FJ9JkmK6/NzSzS2pZteuIaDFIdNh3z65Xw0tLcAfUL8YhOcFlVKdZZEb44SG84GJhPS3TSFoC7GNLnhAYTeppqd+LtvQdX3gn1ODtKXd7X5+/A7wCwkihay+qh+K6dy2qkewnqUUwOFcE5bBkuUBzyPoJ5SxPFOG2nBJd/a1vS37T09HB4ErzGs7QtF/yWijmFuNAc2UIvEg+mp9tDgOrATrkeQIfrMZYoEfdTnfxz8c=
