dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
- openjdk8
before_install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_d472159ded8f_key
  -iv $encrypted_d472159ded8f_iv -in .travis/keyrings/deploy_key.pem.enc -out .travis/keyrings/deploy_key.pem
  -d; fi
- export PATH=$PATH:${TRAVIS_BUILD_DIR}/target
- echo "MAVEN_OPTS='-Xmx2g -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djava.security.egd=file:/dev/./urandom'"
  > ~/.mavenrc
install:
- sudo apt-get install -y gnupg2
script:
- mvn --settings .travis/settings.xml clean test -B -U
after_success:
- mvn --settings .travis/settings.xml coveralls:report
cache:
  directories:
  - "$HOME/.m2"
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    repo: nats-io/java-nats
    branch: master
    jdk: oraclejdk8
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    repo: nats-io/java-nats
    tags: true
    jdk: oraclejdk8
env:
  global:
  - GPG_DIR=${TRAVIS_BUILD_DIR}/.travis/keyrings
  - secure: UghnlxFN5cnn+k1mAok3MuoiD8DSr2ClpAXfAoir4W73LP9XPzPhkY9Op9eX2ePOgg+IkW9UAAGHkwx8/JCesYr3NkLrpQptDuIXA3BBUxS4eW87ucPe5VAu81HY9Wmne+uxX4iHIHU01OH5TVicpDDUz8N5FNj0uWJl3tQpuxE81mSuBwmBkhgM3eKDMuqYyLK5THe/lUkhNf0tYZatFOONbJUGSrL6CMI1yXIZ2sRcMVI2uSBXuCt7b7vgXJ8NaGJQoP+4aYGfJakVIbGCH8ZsXa8pbhOJ44goXploosQfPTahlaRV85Vo+ME/4nnxiBsxJW3+1O7KSxR2PwgURlVMEAJzk6pJBNtdni7BdF4x9pVm8ZNRbXWDAHjrT8hbpo6ppHQ2Y8a7qZA7obEEAMjED1jywRylWSPYNE+tDzkXXeOMBJpEyNA9pPsPnYkd6VYTy9r7wUl3FYTGTvezE8wnLVVz4vO8ccJpQv8F+gq+HrXXgTREJWfT69Ysb4/SVnuXHiYmKgFcv6lziIlvsQr1e2fl+M1vp8dJq53pLQCwZISr1Zx1nwpLo2HGAaLyd3R1suIUyTT21Q5rEyPMmJcRK/T0lp1n9G5vn1hPow73csnirz9zgQxamu/vSZ/gphDDyAMiVi/AwpY9pcRyRU4iSSsHoWefkf4eUB3Ys84=
  - secure: ilhoMizB6jF1ocDmYMnWF/ls8HVuMSkz1s4ro8RmPGtsZgLwI6caOh+Btwgb2t1ab6/Q4nCEePsYFhOEUmLBNJImWr3SWs8n/wlQrMAd/mx0PoyNVK4W1pqjRh7vQ1JguWAzerI0Isl136JfJGoruRKoZxzlF4eNCQ0hw8sceBVfNWiZpO+O9Y461GdcvB2pajUs+xYZG/UuhqfSyEKktIzvHNZ6J6AV9wKx06OFj8+hjPxreJ0TOZY7B/lDlnnvP43RimCS47CP4UOd/bhVK5Ha3GrB+naP6S430ESaQ0RqooEgKrtlRTaXLaxMCvgZ6SaJD5Vj/eKczu+XVd6G5icTym1zsWPz1JizfPsBigFimR1vACCjRJsZ0NGNuCTwqNtgizUAEsb9EBmpTdvrTpK4SDGb6H2piaz++rhlRWFGOO8S+mOztwwLZdR+ZkcNBwoPd0d2DQ1SEWVLNcH1Ss6dfGxK2PZ7jJBfXIscD0MnAIJZbUcoH889zdlZQcOc9CMuzojl1JWohsknye0TN1dG4GRJd4AHRf2y1Pgx/7S4eQ17fCv+r/UFhJCVaqru7t+5JXmkoPSgJ2Tfe+VxbNsmC1XW5AuONoFP58XImeF9nyWtLIWd83EL+0BHisKc6B+CTO7iw+igwtY8CmXBzmKJ/vYGoEMlO3LjKPn5Hgc=
  - secure: McGeju/mV1ChXPpPY+a+MIoRcpOurPXfH93igIgGd3wnvFzh8o3rPmgtcuIlGmN3ijD13QzxO9Va+rw6AzSvLZn3LxDCoTOUWIvxLRIiBb1s/DtJW8q3nLgp7QmGg5NFzRG/Qmb8QUjpENMErqPSg4tB5QZM4++PVRHNUp/Vzjtt46++z1KlH5e4bzFX+O254IHkvsVobuoCScWzX/UYkhJJpiIcKTAqAn0lHkK0exlrCmyJAMKO4G8OVWOZXwjCEUYIuKbuwPvELSwbRv9fsPOWGV2N3G+pm4hUeN5i8kKvcx5RISuqw6YUJx4Ifv2xbcXdVpVxd8MSKWs7pN05KsiEsCxNe6JwCiWqT20XVuQmjacv9pSHwo41x6KjwMeUqSo7wcF4h/xcrvTT9z8lulcoyB6bF/iYd/cSpqncgbRAucLQQyfppeSKeszpUbeWfxdtrio4KKShBNYn55U+ggz/zVrUUx82Bjq6/EUOCmhlsw6kXLnbjXcl/vl6HYO+PTyopgv/wQZ2z9ksX5doa/Tk3dw9DyN8ttJesZx9XlSvw/HHhzsLUGkQdvEO3FKdyMjJ9UCwsFr+gDYdZ9dM1eClL3O0gX3VID9AGth6k+44eui9+dGLlC0aybm2oXHW6xECvldg2DAW1CV4V2W648vgZQiz5GALHhO3gDC4sLo=
  - secure: XFtIXlFcv4F5+H/VVzjawAznEaO5chsSY7FstCyE1F6YlKODunGUumTR22yx7cRYBzIzvN0y/sgRGMJbNPUPWObRrLED77U27UBJZMdKDD5KlZr6LgJxG+iQQlZaE5oqcio2ngJkulo5eLACKsapYtc1nC2/80tj/8Qak0u6gV5A53P3hTAjYveRW0zyTF8FqidT2i/lDGgwEKlWFtBbFgJrPUgE8N+4ao4jxj/9H+VP7HYojygzcohwe7r9Y/5BOMDvCx/7fk7jnE+k+FpUo2P/3HgDqpg/sqiCH234L+gSV/rV6H3xob2FUBprVq7TpFuxgsUzc0hTphMR2I911sVWQYvVhHyja2pFckygRIHnRdXTi/GuHDhSVbgIDNRk7bQaClRewBMMQ0gCrEeiWrQ7KvjmoAUF4q18ApgROer12jijXiZoe+fTevU7ki3r1z0MzXt0Z69ug0HkswyRaK1oD1MwmgBtHxWaKxH6uQPreDAcava023P8QErkK8bsDECHIsrTnqi5SjdUwJFDFHt3m81MhUDzlOAFa9kgqh48UEV0MkN1fXzSmwwbjvYdS4NINOB/AIcuYKfI5AyPOS47/CMx3gthr/+oS7muHjqfP7b1r508zUdJlckGf0FDGROZREglgu9AMJAexzmFXM/EtmYzAc+mvOdOmjfkBNA=
  - secure: IXvvz6nl+GSUmgl7PhI2ynWxN0KUFmcQbfk3851JL9mxnQyl6XnGM6/ox1/m5UYt/FfCg7EJOyyud+XL0c2/qkWnTt6rrTKoV5Rq1hNE+BRaQNvUiO+d0nPdmqzFA4Uzk5rzYdj2+3uUEZKKk0c7dV56rBOOL4vOqngU8TkX0Q+cQ/3DpZdvIc4Ky4q3YKgqeXitujV8dFcGfZB4F8bt6zL3XLIwXEBH+rC5JsGbyS1WLTz1/Fmfyp9MECf3X3R/pInYuxTVLZrn2JfSRBcKwvnpgT548HR1JyUEyKbksDDNDLoQRzZ0bnk/6ZOS5zig//VmViEnwwOpIND012rQfI5seN7FBvbCG6f1vGPhi653OOiiiCiZvEhjvnReSXynrtJflZseEYuR9W3mpQ4GLjyA9wpCOiy62Jv+FO8cPfHBnTPatZyWSZ0/dH8LgDD0Ay98EV+pAYfIk9Ml4LEPTpZhNKaqBGVppm0cxi2Ym30jP8iETgGic8/CHLD4W57oyhLy8s9dOY76+RsAtTkphjCe1PAy4c9TqNGTUk/KwahIOzydMvXnT4HUPjym0vnW5QxMLZtD6BAzYiNFNQbqvUJKM049RYpVxxkAyMMQ2gk3/6nchY7wBna1PySneUI+dkdqNd3mNXPfMdpViUqHUO5Wjm0ZYxTO6m1AjjLXs34=
